### ISSUE TITLE
Binaries available?

### ISSUE THREAD

**Issue by JinxDojo** [cppcooper/RegexRenamer#1]
Hi cppcooper,

Thank you for your reply on https://github.com/markusdosch/RegexRenamer/issues/4 ! I appreciate you referencing your recursive version. I'm hoping you also have made binaries available, but I don't see them in the release ZIP files. Could you please advise?

Thanks again!

**Comment by cppcooper** [comment]
It feels like half a decade since I looked at this code, I have no idea why I made any of the changes I made. In any case, all I did was make the changes I needed and build.. then tested the changes. I think I was renaming all the episodes of 'Dragonball' to correspond to saga and such. So I would have just used the binaries built, probably built for debugging even.

You'll have to build it if you want the changes I made which allowed me to perform recursion on whatever.. I think it was directories. I think I may have even left it with hard coding for the max recursion depth. I don't remember anything at all.

I won't be providing binaries.

The changes are here either way,
https://github.com/cppcooper/RegexRenamer/commit/1b90bf5ad39f4d2d03b37b0d8e84222426b911b4

Also if you need some help, you might check here for my email.
https://github.com/cppcooper/RegexRenamer/commit/1b90bf5ad39f4d2d03b37b0d8e84222426b911b4.patch

**Comment by JinxDojo** [comment]
Thank you for the reply. Unfortunately, compiling myself is probably beyond my expertise/resources, especially given I'm currently working from a computer that isn't even mine. Nevertheless, I appreciate your answer and offer to help via e-mail.

Thanks again
